// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxdnmvzemzhrscoesqyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZG5tdnplbXpocnNjb2VzcXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzk5ODUsImV4cCI6MjA2Njg1NTk4NX0.k7E2XEjd-HA1mCsYYut8Huvtkc6vq9ACAty49vONc7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});